import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '../../../contexts/AuthContext';
import { disableApp, grantApp, listApps, type AppGrant, type PlatformApp } from './api';

export function AppsPage() {
  const { session, tenant } = useAuth();
  const auth = useMemo(() => ({ accessToken: session?.access_token, tenantId: tenant?.id }), [session?.access_token, tenant?.id]);
  const [apps, setApps] = useState<PlatformApp[]>([]); const [grants, setGrants] = useState<AppGrant[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const [query, setQuery] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const data = await listApps(auth); setApps(data.apps); setGrants(data.grants); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load apps'); } finally { setLoading(false); } }, [auth]);
  useEffect(() => { void load(); }, [load]);
  const active = new Set(grants.filter(g => g.status === 'active').map(g => g.app_key));
  const visible = apps.filter(app => `${app.name} ${app.description || ''}`.toLowerCase().includes(query.toLowerCase()));
  async function toggle(app: PlatformApp) { setBusy(app.id); setError(''); try { if (active.has(app.id)) await disableApp(auth, app.id); else await grantApp(auth, app); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'App update failed'); } finally { setBusy(''); } }
  return <div className="rsx-panel"><div className="rsx-panel__head"><div><div className="rsx-panel__eyebrow">Workspace apps</div><p className="rsx-panel__lead">Grant only the capabilities each workspace needs, then open connected apps directly.</p></div></div>
    {error && <div className="rsx-note" role="alert"><div className="rsx-note__title">Apps unavailable</div><div className="rsx-note__body">{error}</div><button className="rsx-row__btn" onClick={() => void load()}>Retry</button></div>}
    {loading ? <div className="rsx2-empty"><div className="rsx2-empty__text">Loading apps…</div></div> : apps.length === 0 ? <div className="rsx2-empty"><div className="rsx2-empty__icon">◇</div><div className="rsx2-empty__title">No apps published</div><div className="rsx2-empty__text">The platform catalog returned no apps for this workspace.</div></div> : <><div className="rsx-stats"><div className="rsx-stat"><strong>{active.size}</strong><span>Active</span></div><div className="rsx-stat"><strong>{apps.length}</strong><span>Available</span></div></div><div className="rsx-form"><label className="rsx-form__field"><span className="rsx-form__label">Find an app</span><input className="rsx-form__input" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search apps" /></label></div>{visible.length === 0 ? <div className="rsx2-empty"><div className="rsx2-empty__title">No matching apps</div><div className="rsx2-empty__text">Try another name or keyword.</div></div> : <div className="rsx-cards">{visible.map(app => { const enabled = active.has(app.id); const unavailable = app.status === 'planned'; return <article className="rsx-card" key={app.id}><div className="rsx-card__top"><div className="rsx-card__icon">{app.icon || app.name.slice(0, 2).toUpperCase()}</div><div className="rsx-card__title">{app.name}</div></div><div className="rsx-card__desc">{app.description || 'No description provided by the app catalog.'}</div><div className="rsx-card__desc">{(app.required_scopes || []).length ? `Access: ${(app.required_scopes || []).join(', ')}` : 'No additional scopes requested.'}</div><div className="rsx-card__foot"><span className={`rsx-badge rsx-badge--${enabled ? 'on' : unavailable ? 'warn' : 'off'}`}>{enabled ? 'Active' : unavailable ? 'Planned' : 'Available'}</span>{enabled && app.url && <a className="rsx-card__btn" href={app.url} target="_blank" rel="noreferrer">Open</a>}<button className="rsx-card__btn" disabled={Boolean(busy) || unavailable} onClick={() => void toggle(app)}>{busy === app.id ? 'Updating…' : enabled ? 'Disable' : unavailable ? 'Coming soon' : 'Enable'}</button></div></article>; })}</div>}</>}
  </div>;
}

