import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '../../../contexts/AuthContext';
import { disableApp, grantApp, listApps, listCapabilityResources, type AppGrant, type CapabilityResource, type PlatformApp } from './api';

type Tab = 'apps' | 'connectors' | 'plugins' | 'skills' | 'agents';
const TABS: Array<{ id: Tab; label: string }> = [
  { id: 'apps', label: 'Apps' }, { id: 'connectors', label: 'Connectors' }, { id: 'plugins', label: 'Plugins' },
  { id: 'skills', label: 'Skills' }, { id: 'agents', label: 'Agents' },
];
const CONNECTORS = [['gmail','Gmail','Email and calendar workflows'], ['google-drive','Google Drive','Files and grounded retrieval'], ['hubspot','HubSpot','CRM workflows'], ['slack','Slack','Messages, alerts, and approvals']] as const;
const PLUGINS = [['mcp-client','Universal MCP Client','Connect approved MCP servers'], ['retail-toolkit','Retail Operations Toolkit','Store-aware operations tools']] as const;
const AGENTS = [['ellie','Ellie','Store concierge and specialist router'], ['ana','Ana','Inventory intelligence'], ['sammy','Sammy','Revenue intelligence']] as const;

export function MarketplacePage() {
  const { session, tenant } = useAuth();
  const auth = useMemo(() => ({ accessToken: session?.access_token, tenantId: tenant?.id }), [session?.access_token, tenant?.id]);
  const [tab, setTab] = useState<Tab>('apps');
  const [apps, setApps] = useState<PlatformApp[]>([]); const [grants, setGrants] = useState<AppGrant[]>([]); const [skills, setSkills] = useState<CapabilityResource[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<PlatformApp | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [catalog, skillData] = await Promise.all([listApps(auth), listCapabilityResources(auth, 'skill')]); setApps(catalog.apps); setGrants(catalog.grants); setSkills(skillData); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load Marketplace'); } finally { setLoading(false); } }, [auth]);
  useEffect(() => { void load(); }, [load]);
  const active = new Set(grants.filter(grant => grant.status === 'active').map(grant => grant.app_key));
  async function toggle(app: PlatformApp) { setBusy(app.id); setError(''); try { if (active.has(app.id)) await disableApp(auth, app.id); else await grantApp(auth, app); await load(); setSelected(null); } catch (e) { setError(e instanceof Error ? e.message : 'App update failed'); } finally { setBusy(''); } }
  const q = query.toLowerCase();
  const catalog = tab === 'connectors' ? CONNECTORS : tab === 'plugins' ? PLUGINS : AGENTS;
  return <div className="rsx-panel rsx-marketplace-layout">
    <div className="rsx-panel__head"><div><div className="rsx-panel__eyebrow">Marketplace</div><p className="rsx-panel__lead">Discover apps and review their access before activating them.</p></div></div>
    <div className="rsx2-tabs" role="tablist">{TABS.map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} className={`rsx2-tab ${tab === item.id ? 'is-on' : ''}`} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>
    <div className="rsx-form"><label className="rsx-form__field"><span className="rsx-form__label">Search Marketplace</span><input className="rsx-form__input" value={query} onChange={event => setQuery(event.target.value)} placeholder={`Search ${tab}`} /></label></div>
    {error && <div className="rsx-note" role="alert"><div className="rsx-note__title">Marketplace unavailable</div><div className="rsx-note__body">{error}</div><button className="rsx-row__btn" onClick={() => void load()}>Retry</button></div>}
    {tab === 'apps' ? loading ? <Empty text="Loading apps…" /> : <div className="rsx-cards">{apps.filter(app => `${app.name} ${app.description || ''}`.toLowerCase().includes(q)).map(app => { const enabled = active.has(app.id); const unavailable = app.status === 'planned'; return <article className="rsx-card" key={app.id}><div className="rsx-card__top"><div className="rsx-card__icon">{app.icon || app.name.slice(0,2).toUpperCase()}</div><div className="rsx-card__title">{app.name}</div></div><div className="rsx-card__desc">{app.description || 'AROS application'}</div><div className="rsx-card__desc">{(app.required_scopes || []).length ? `Access: ${app.required_scopes!.join(', ')}` : 'No additional scopes requested.'}</div><div className="rsx-card__foot"><span className={`rsx-badge rsx-badge--${enabled ? 'on' : unavailable ? 'warn' : 'off'}`}>{enabled ? 'Active' : unavailable ? 'Planned' : 'Inactive'}</span>{enabled && app.url && <a className="rsx-card__btn" href={app.url} target="_blank" rel="noreferrer">Open dashboard</a>}<button className="rsx-card__btn" disabled={Boolean(busy) || unavailable} onClick={() => setSelected(app)}>{unavailable ? 'Coming soon' : enabled ? 'Configure' : 'Activate'}</button></div></article>; })}</div>
      : tab === 'skills' ? loading ? <Empty text="Loading skills…" /> : skills.length === 0 ? <Empty text="No skills are published to this workspace yet." /> : <div className="rsx-cards">{skills.filter(item => `${item.name} ${item.provider || ''} ${(item.capabilities || []).join(' ')}`.toLowerCase().includes(q)).map(item => <article className="rsx-card" key={item.id}><div className="rsx-card__top"><div className="rsx-card__icon">Sk</div><div className="rsx-card__title">{item.name}</div></div><div className="rsx-card__desc">{(item.capabilities || []).join(', ') || item.provider || 'Workspace skill'}</div><div className="rsx-card__foot"><span className={`rsx-badge rsx-badge--${item.status === 'active' ? 'on' : 'off'}`}>{item.status || 'Inactive'}</span><a className="rsx-card__btn" href="/skills">View details</a></div></article>)}</div>
      : <div className="rsx-cards">{catalog.filter(item => `${item[1]} ${item[2]}`.toLowerCase().includes(q)).map(item => <article className="rsx-card" key={item[0]}><div className="rsx-card__top"><div className="rsx-card__icon">{item[1].slice(0,2).toUpperCase()}</div><div className="rsx-card__title">{item[1]}</div></div><div className="rsx-card__desc">{item[2]}</div><div className="rsx-card__foot"><span className="rsx-badge rsx-badge--warn">Catalog</span><button className="rsx-card__btn" disabled title="Tenant-scoped authorization bridge required">Coming soon</button></div></article>)}</div>}
    {selected && <div className="setup-modal-backdrop" onMouseDown={event => { if (event.currentTarget === event.target) setSelected(null); }}><div className="setup-modal" role="dialog" aria-modal="true" aria-label={`${selected.name} profile`}><div className="modal-title"><div><p className="setup-eyebrow">App profile</p><h2>{selected.name}</h2></div><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close">×</button></div><div className="connection-form"><p className="modal-copy">{selected.description || 'AROS application'}</p><div className="permission-review"><strong>Requested access</strong>{(selected.required_scopes || []).length ? selected.required_scopes!.map(scope => <label key={scope}><input type="checkbox" checked readOnly /> {scope}</label>) : <p>No additional scopes requested.</p>}</div><div className="rsx-note"><div className="rsx-note__title">Related capabilities</div><div className="rsx-note__body">This catalog does not yet publish the skills, agents, and tools bundled with this app. Activation currently grants the app scopes only.</div></div>{selected.repo && <p className="modal-copy">Source: {selected.repo}</p>}<div className="modal-actions"><button className="setup-secondary" onClick={() => setSelected(null)}>Cancel</button><button className="setup-primary" disabled={busy === selected.id} onClick={() => void toggle(selected)}>{busy === selected.id ? 'Updating…' : active.has(selected.id) ? 'Inactivate app' : 'Activate app'}</button></div></div></div></div>}
  </div>;
}

function Empty({ text }: { text: string }) { return <div className="rsx2-empty"><div className="rsx2-empty__text">{text}</div></div>; }
