import { generateKeyPair, exportJWK, SignJWT } from 'jose';
import { describe, expect, it } from 'vitest';
import { AROS_APPLICATION, createOidcRelyingParty } from '../oidc-rp';

async function harness(overrides: { issuer?: string; nonce?: string; workspace?: string; allow?: boolean } = {}) {
  const { privateKey, publicKey } = await generateKeyPair('RS256'); const jwk = await exportJWK(publicKey); Object.assign(jwk, { kid: 'test', alg: 'RS256', use: 'sig' });
  let authorize = new URL('https://invalid');
  const fetcher = async (input: string | URL | Request) => { const url = String(input); if (url.includes('jwks')) return Response.json({ keys: [jwk] }); if (url.includes('openid-configuration')) return Response.json({ issuer: AROS_APPLICATION.issuer, authorization_endpoint: `${AROS_APPLICATION.issuer}/oauth/authorize`, token_endpoint: `${AROS_APPLICATION.issuer}/oauth/token`, jwks_uri: `${AROS_APPLICATION.issuer}/.well-known/jwks.json`, revocation_endpoint: `${AROS_APPLICATION.issuer}/oauth/revoke` }); if (url.includes('/oauth/token')) { const token = await new SignJWT({ nonce: overrides.nonce || authorize.searchParams.get('nonce'), workspace_id: overrides.workspace || 'workspace-1', scope: 'openid' }).setProtectedHeader({ alg: 'RS256', kid: 'test' }).setIssuer(overrides.issuer || AROS_APPLICATION.issuer).setAudience('aros-api').setSubject('user-1').setExpirationTime('5m').sign(privateKey); return Response.json({ id_token: token, refresh_token: 'test-refresh', expires_in: 300 }); } return Response.json({}); };
  const rp = createOidcRelyingParty({ fetcher: fetcher as typeof fetch, mapWorkspace: async (_sub, workspace) => overrides.allow === false ? null : { workspaceId: workspace!, role: 'owner' } });
  const start = await rp.begin({ returnTo: '/dashboard' }); authorize = new URL(start.location); const browser = start.setCookie.split(';')[0];
  return { rp, authorize, browser };
}

describe('AROS OIDC relying party', () => {
  it('uses authorization code with S256 PKCE, state, and nonce', async () => { const { authorize } = await harness(); expect(authorize.searchParams.get('response_type')).toBe('code'); expect(authorize.searchParams.get('code_challenge_method')).toBe('S256'); expect(authorize.searchParams.get('state')).toBeTruthy(); expect(authorize.searchParams.get('nonce')).toBeTruthy(); });
  it('creates an opaque server session bound to workspace and role', async () => { const { rp, authorize, browser } = await harness(); const result = await rp.callback({ code: 'code', state: authorize.searchParams.get('state')!, cookie: browser }); const session = await rp.authenticate(result.setCookie); expect(session?.workspaceId).toBe('workspace-1'); expect(rp.authorize(session, 'workspace-1', ['owner'])).toBe(true); expect(rp.authorize(session, 'other', ['owner'])).toBe(false); });
  it('rejects replayed state, wrong browser, issuer, nonce, and workspace access', async () => { const valid = await harness(); const state = valid.authorize.searchParams.get('state')!; await expect(valid.rp.callback({ code: 'x', state, cookie: 'aros_oidc_browser=wrong' })).rejects.toThrow(/state/); await valid.rp.callback({ code: 'x', state, cookie: valid.browser }); await expect(valid.rp.callback({ code: 'x', state, cookie: valid.browser })).rejects.toThrow(/state/); const issuer = await harness({ issuer: 'https://evil.example' }); await expect(issuer.rp.callback({ code: 'x', state: issuer.authorize.searchParams.get('state')!, cookie: issuer.browser })).rejects.toThrow(); const nonce = await harness({ nonce: 'wrong' }); await expect(nonce.rp.callback({ code: 'x', state: nonce.authorize.searchParams.get('state')!, cookie: nonce.browser })).rejects.toThrow(/nonce/); const denied = await harness({ allow: false }); await expect(denied.rp.callback({ code: 'x', state: denied.authorize.searchParams.get('state')!, cookie: denied.browser })).rejects.toThrow(/Workspace/); });
  it('revokes and clears the local session on logout', async () => { const { rp, authorize, browser } = await harness(); const result = await rp.callback({ code: 'x', state: authorize.searchParams.get('state')!, cookie: browser }); const logout = await rp.logout(result.setCookie); expect(logout.setCookie).toContain('Max-Age=0'); expect(await rp.authenticate(result.setCookie)).toBeNull(); });
});
