import { useState } from 'react';
type Kind = 'channels' | 'agents' | 'skills';
const DATA = {
  channels: { title: 'Message channels', copy: 'Choose where people reach the Shreai router. Each channel inherits workspace identity, permissions, and audit policy.', action: 'Connect channel', items: [['AROS Chat','Native workspace chat and command surface.','Native',true],['WhatsApp','Messaging through a verified business account.','Messaging',false],['Slack','Commands, alerts, and approval workflows.','Collaboration',false],['Microsoft Teams','Enterprise chat and approval cards.','Collaboration',false],['AI clients','Claude, Codex, Gemini, Sia, and compatible clients.','Agent protocol',false]] },
  agents: { title: 'Agents', copy: 'Agents coordinate goals and invoke approved skills. They cannot access tools outside their assigned scope.', action: 'Create agent', items: [['Store Operations Agent','Monitors daily operations, exceptions, and store health.','Operations',true],['Inventory Agent','Tracks stock and drafts replenishment actions.','Inventory',true],['Pricing Agent','Proposes approval-gated POS changes.','Approval required',false],['Customer Support Agent','Handles support using connected systems.','Support',false],['Finance Agent','Reconciles POS and accounting activity.','Finance',false]] },
  skills: { title: 'Skills', copy: 'Versioned, reusable procedures that agents invoke through policy-controlled tools.', action: 'Add skill', items: [['Daily Sales Summary','Queries mapped POS stores and produces a cited summary.','Read only',true],['Inventory Reorder','Builds reorder recommendations from stock velocity.','Draft action',true],['Price Update','Submits a POS price change after approval.','Write action',false],['Support Triage','Classifies tickets and drafts responses.','Draft action',false],['Store Closeout','Runs end-of-day checks and reports exceptions.','Workflow',false]] },
} satisfies Record<Kind, { title: string; copy: string; action: string; items: Array<[string,string,string,boolean]> }>;

export function CapabilityCatalog({ kind }: { kind: Kind }) {
  const data = DATA[kind]; const [items,setItems] = useState(data.items);
  const toggle=(name:string)=>setItems(all=>all.map(i=>i[0]===name?[i[0],i[1],i[2],!i[3]]:i));
  return <section className="setup-page"><header className="setup-header"><div><p className="setup-eyebrow">Shreai router</p><h1>{data.title}</h1><p>{data.copy}</p></div><button className="setup-primary">{data.action}</button></header>
    <div className="setup-summary"><div><strong>{items.length}</strong><span>Available</span></div><div><strong>{items.filter(i=>i[3]).length}</strong><span>Active</span></div><div><strong>{items.filter(i=>!i[3]).length}</strong><span>Not configured</span></div></div>
    <div className="catalog-grid">{items.map(([name,copy,tag,active])=><article className="setup-panel catalog-card" key={name}><div className="catalog-card-head"><div className="provider-mark">{name.slice(0,2).toUpperCase()}</div><span className={`status-pill ${active?'connected':'inactive'}`}>{active?'Active':'Inactive'}</span></div><h2>{name}</h2><p>{copy}</p><div className="catalog-card-foot"><span>{tag}</span><button className="setup-secondary" onClick={()=>toggle(name)}>{active?'Disable':'Configure'}</button></div></article>)}</div>
  </section>;
}
